language: python

python:
    - "2.7"

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libnotify
    - pip install requests

script:
    - nosetests

notifications:
    email: false
