language: python

python:
    - "2.7"
    - "3.3"
    - "3.4"

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libnotify-bin
    - pip install -r requirements.txt
    - pip install coveralls

script:
    - nosetests -v --with-coverage --cover-package=wonderful_bing

after_success:
    - coveralls

notifications:
    email: false
